//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP2TP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDP2TP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добрый день, {RequesterName}.
        /// 
        ///Ваша заявка была перенесена в Систему Управления Разработкой бизнес-приложений под новым номером &lt;span style=&quot;font-weight:bold;&quot;&gt;{tp_request_ID}&lt;/span&gt;, просьба использовать его при уточнении статуса выполнения заявки. 
        ///К сожалению мы не можем назвать точного срока исполнения вашего запроса, но как только мы выполним ваш запрос, вы получите письмо с уведомлением.
        /// 
        ///Ответственным за разработку назначен: &lt;span style=&quot;font-weight:bold;&quot;&gt;{developerName}&lt;/span&gt;
        /// 
        ///--- Просьб [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDP_Resolution {
            get {
                return ResourceManager.GetString("SDP_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SELECT nwo.NOTIFICATIONID ID, 
        ///	from_unixtime(n.NOTIFICATIONDATE / 1000) MessageDate,
        ///	n.SENDERID SenderID, 
        ///	au.FIRST_NAME SenderFullName, 	
        ///	aci.EMAILID SenderEmail,
        ///	n2d.description Description	
        ///FROM notify_workorder nwo 
        ///	left join notificationtodesc n2d 
        ///		on nwo.NOTIFICATIONID = n2d.NOTIFICATIONID
        ///-- 	left join aaauser au
        ///	left join notification n
        ///		on nwo.NOTIFICATIONID = n.NOTIFICATIONID
        ///		left join aaauser au
        ///		on n.SENDERID = au.USER_ID
        ///	left join aaausercontactinfo auci
        ///		on n.SEN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDP_select_Messages_by_workorderID_sql {
            get {
                return ResourceManager.GetString("SDP_select_Messages_by_workorderID_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select wo.WORKORDERID, 
        ///	(select aci.EMAILID 
        ///	from aaacontactinfo aci
        ///	where aci.CONTACTINFO_ID = (select auci.CONTACTINFO_ID
        ///								from aaausercontactinfo auci
        ///								where auci.USER_ID = wo.REQUESTERID))	Email,
        ///	(select au.FIRST_NAME
        ///	from aaauser au
        ///	where au.USER_ID = wo.REQUESTERID) FullName,	
        ///	wo.TITLE, 
        ///	wo.DESCRIPTION,
        ///	(select wod.FULLDESCRIPTION
        ///	from workordertodescription wod
        ///	where wod.WORKORDERID = wo.WORKORDERID) FullDescription, 	
        ///	(select sd.Name 
        ///	from servicedefinition  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SDP_Select_requests {
            get {
                return ResourceManager.GetString("SDP_Select_requests", resourceCulture);
            }
        }
    }
}
